import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { auth } from "@/lib/auth";
import Footer from "@/components/footer";
import { Analytics } from "@vercel/analytics/react";
import { FloatingBugButton } from "@/components/FloatingBugButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CarVentory",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Analytics />
        <Navbar session={session} />
        {children}
        <Footer />
        {session && session.user && <FloatingBugButton />}
      </body>
    </html>
  );
}